import { Skill } from '@models';
import { nanoid } from 'nanoid';

export enum TechnosList {
  Python = 'Python',
  LLM = 'LLM',
  RAG = 'RAG',
  GenAI = 'Gen AI',
  Llama3 = 'LLAMA 3',
  LangChain = 'LangChain',
  ChromaDB = 'ChromaDB',
  Ollama = 'Ollama',
  SentenceTransformers = 'SentenceTransformers',
  Numpy = 'Numpy',
  Pandas = 'Pandas',
  ScikitLearn = 'Scikit-Learn',
  Scipy = 'Scipy',
  OpenCV = 'OpenCV',
  Keras = 'Keras',
  PyTorch = 'PyTorch',
  TensorFlow = 'TensorFlow',
  Matplotlib = 'Matplotlib',
  Plotly = 'Plotly',
  HuggingFace = 'Hugging Face',
  MLFlow = 'MLFlow',
  WeightsAndBiases = 'Weights & Biases',
  VectorDB = 'Vector DB',
  FastAPI = 'FastAPI',
  Docker = 'Docker',
  Pytest = 'Pytest',
  Git = 'Git',
  GitHub = 'GitHub',
  NodeJS = 'Node.js',
  Metaflow = 'Metaflow',
  AWS = 'AWS',
  GCP = 'Google Cloud',
  Anaconda = 'Anaconda',
  Jupyter = 'Jupyter',
  MLOps = 'MLOps',
}

// logo field now holds the PUBLIC URL path to static/skills/ images
export const TechnosConstant: Skill[] = [
  { title: TechnosList.Python,               logo: '/skills/Python.png',                      color: '#3776AB', id: nanoid(4) },
  { title: TechnosList.TensorFlow,           logo: '/skills/TensorFlow.png',                  color: '#FF6F00', id: nanoid(4) },
  { title: TechnosList.PyTorch,              logo: '/skills/PyTorch.png',                     color: '#EE4C2C', id: nanoid(4) },
  { title: TechnosList.Keras,                logo: '/skills/Keras.png',                       color: '#D00000', id: nanoid(4) },
  { title: TechnosList.ScikitLearn,          logo: '/skills/scikit-learn.png',                color: '#F7931E', id: nanoid(4) },
  { title: TechnosList.LangChain,            logo: '/skills/LANGCHAIN.svg',                   color: '#1C3C3C', id: nanoid(4) },
  { title: TechnosList.HuggingFace,          logo: '/skills/🤗 HUGGING FACE.svg',             color: '#FFD21E', id: nanoid(4) },
  { title: TechnosList.FastAPI,              logo: '/skills/FastAPI.png',                     color: '#009688', id: nanoid(4) },
  { title: TechnosList.Docker,               logo: '/skills/Docker.png',                      color: '#2496ED', id: nanoid(4) },
  { title: TechnosList.OpenCV,               logo: '/skills/OpenCV.png',                      color: '#5C3EE8', id: nanoid(4) },
  { title: TechnosList.Numpy,                logo: '/skills/NumPy.png',                       color: '#013243', id: nanoid(4) },
  { title: TechnosList.Pandas,               logo: '/skills/Pandas.png',                      color: '#150458', id: nanoid(4) },
  { title: TechnosList.Plotly,               logo: '/skills/PLOTLY.svg',                      color: '#3F4F75', id: nanoid(4) },
  { title: TechnosList.Matplotlib,           logo: '/skills/Matplotlib.png',                  color: '#11557C', id: nanoid(4) },
  { title: TechnosList.ChromaDB,             logo: '/skills/CHROMADB.svg',                    color: '#FF6B35', id: nanoid(4) },
  { title: TechnosList.MLFlow,               logo: '/skills/MLFLOW.svg',                      color: '#0194E2', id: nanoid(4) },
  { title: TechnosList.NodeJS,               logo: '/skills/Node.js.png',                     color: '#339933', id: nanoid(4) },
  { title: TechnosList.GitHub,               logo: '/skills/GitHub.png',                      color: '#24292E', id: nanoid(4) },
  { title: TechnosList.Git,                  logo: '/skills/Git.png',                         color: '#F05032', id: nanoid(4) },
  { title: TechnosList.Pytest,               logo: '/skills/pytest.png',                      color: '#0A9EDC', id: nanoid(4) },
  { title: TechnosList.Scipy,                logo: '/skills/SCIPY.svg',                       color: '#8CAAE6', id: nanoid(4) },
  { title: TechnosList.VectorDB,             logo: '/skills/VECTOR DB.svg',                   color: '#7C3AED', id: nanoid(4) },
  { title: TechnosList.RAG,                  logo: '/skills/RAG.svg',                         color: '#E53E3E', id: nanoid(4) },
  { title: TechnosList.Ollama,               logo: '/skills/OLLAMA.svg',                      color: '#222222', id: nanoid(4) },
  { title: TechnosList.SentenceTransformers, logo: '/skills/SENTENCE TRANSFORMERS.svg',       color: '#FF9900', id: nanoid(4) },
  { title: TechnosList.WeightsAndBiases,     logo: '/skills/WEIGHTS & BIASES.svg',            color: '#FFBE00', id: nanoid(4) },
  { title: TechnosList.Metaflow,             logo: '/skills/METAFLOW.svg',                    color: '#6236FF', id: nanoid(4) },
  { title: TechnosList.LLM,                  logo: '/skills/LLM.svg',                         color: '#7B2D8B', id: nanoid(4) },
  { title: TechnosList.GenAI,                logo: '/skills/GEN AI.svg',                      color: '#00BCD4', id: nanoid(4) },
  { title: TechnosList.Llama3,               logo: '/skills/LLAMA 3.svg',                     color: '#1565C0', id: nanoid(4) },
  { title: TechnosList.AWS,                  logo: '/skills/AWS.png',                         color: '#FF9900', id: nanoid(4) },
  { title: TechnosList.GCP,                  logo: '/skills/Google Cloud.svg',                color: '#4285F4', id: nanoid(4) },
  { title: TechnosList.Anaconda,             logo: '/skills/Anaconda.png',                    color: '#44A833', id: nanoid(4) },
  { title: TechnosList.Jupyter,              logo: '/skills/Jupyter.png',                     color: '#F37626', id: nanoid(4) },
  { title: TechnosList.MLOps,                logo: '/skills/MLOPS.svg',                       color: '#6C3483', id: nanoid(4) },
];
