// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/22/2026, 2:58:29 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.cjs";
import cfg3 from "./../../tailwind.config.cjs";
const config = [
{"content":{"files":["/Users/akilan/Downloads/AkilanPortfolio/src/components/**/*.{vue,js,mjs,ts}","/Users/akilan/Downloads/AkilanPortfolio/src/layouts/**/*.{vue,js,mjs,ts}","/Users/akilan/Downloads/AkilanPortfolio/src/pages/**/*.{vue,js,mjs,ts}","/Users/akilan/Downloads/AkilanPortfolio/composables/**/*.{js,ts,mjs}","/Users/akilan/Downloads/AkilanPortfolio/utils/**/*.{js,ts,mjs}","/Users/akilan/Downloads/AkilanPortfolio/src/{A,a}pp.{vue,js,mjs,ts}","/Users/akilan/Downloads/AkilanPortfolio/src/{E,e}rror.{vue,js,mjs,ts}","/Users/akilan/Downloads/AkilanPortfolio/src/app.config.{js,ts,mjs}","/Users/akilan/Downloads/AkilanPortfolio/src/app/spa-loading-template.html"]}},
{},
(() => {const cfg=configMerger(undefined, cfg2);cfg.content = cfg.purge;;return cfg;})(),
(() => {const cfg=configMerger(undefined, cfg3);cfg.content = cfg.purge;;return cfg;})()
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;